name: Release

on:
  schedule:
    - cron: "25 9 */3 * *"

permissions:
  id-token: write
  contents: write

jobs:
  release:
    name: Updates languages, releases a new version if needed
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          registry-url: https://registry.npmjs.org

      - name: Verify versions
        run: node --version && npm --version && node -p process.versions.v8

      - name: Install dependencies
        run: |
          npm install

      - name: Update languages
        id: update
        run: |
          MIRAGE_IDENTIFIER=${{ secrets.MIRAGE_IDENTIFIER }} MIRAGE_KEY=${{ secrets.MIRAGE_KEY }} npm run update

      - name: Run tests
        if: ${{ steps.update.outputs.status == 'updated' }}
        run: |
          npm run test

      - name: Bump version
        if: ${{ steps.update.outputs.status == 'updated' }}
        run: |
          npm run bump_version

      - name: Release update
        if: ${{ steps.update.outputs.status == 'updated' }}
        run: |
          npm run release

      - name: Publish package
        if: ${{ steps.update.outputs.status == 'updated' }}
        run: |
          npm publish --provenance
